application: wokanlab-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /console.*
  script: shell.py
  login: admin

- url: /assets
  static_dir: assets

- url: /money.*
  script: money/main.py
  login: admin

- url: /static
  static_dir: static
  expiration: 1d

- url: /.+
  script: main.py

- url: /
  static_files: index.html
  upload: index.html

